# Generated by Django 4.0.3 on 2024-02-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableskill',
            name='category',
            field=models.CharField(default='Coding', max_length=225, unique=True),
        ),
    ]
