# Generated by Django 4.0.3 on 2024-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_skills', '0002_availableskill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableskill',
            name='category',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
