# Generated by Django 4.0.3 on 2024-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_skills', '0004_alter_availableskill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableskill',
            name='category',
            field=models.CharField(choices=[('Web Devlopment', 'Web Devlopment'), ('App Devlopment', 'App Devlopment'), ('MERN Stack', 'MERN Stack'), ('Graphic Designer', 'Graphic Designer'), ('Video Editor', 'Video Editor')], max_length=225),
        ),
    ]
