# Generated by Django 4.0.3 on 2024-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_skills', '0005_alter_availableskill_category'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_preferred',
            field=models.ManyToManyField(related_name='skills_preffered', to='available_skills.availableskill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(related_name='skills_required', to='available_skills.availableskill'),
        ),
    ]
