# Generated by Django 4.0.3 on 2024-02-08 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern_job_application', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_user',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_user_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
