# Generated by Django 4.0.3 on 2024-02-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job_profile', '0007_alter_internjobprofile_expected_salary'),
        ('intern_job_application', '0005_jobapplication_intern_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='intern_job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_user_related', to='intern_job_profile.internjobprofile'),
        ),
    ]
