# Generated by Django 4.0.3 on 2024-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_categoery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
