# Generated by Django 4.0.3 on 2024-02-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_categoery', '0002_jobcategory_display'),
        ('intern_job_profile', '0003_internjobprofile_job_categoery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='job_categoery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_categoery.jobcategory'),
        ),
    ]
