# Generated by Django 4.0.3 on 2024-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job_profile', '0004_alter_internjobprofile_job_categoery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
