# Generated by Django 4.0.3 on 2024-02-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job_profile', '0005_alter_internjobprofile_expected_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
