# Generated by Django 4.0.3 on 2024-02-07 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job_profile', '0006_alter_internjobprofile_expected_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internjobprofile',
            name='expected_salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5000, message='Expected salary must be at least 3000.'), django.core.validators.MaxValueValidator(100000, message='Expected salary must not exceed 1 lakh.')]),
        ),
    ]
