# Generated by Django 4.0.3 on 2024-01-23 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('s2c_certified', models.BooleanField(default=False)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Priority must be at least 1'), django.core.validators.MaxValueValidator(10, message='Priority cannot be above 10')])),
                ('status', models.CharField(max_length=255)),
                ('online_status', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('user_location', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('Caller', 'Caller'), ('View', 'View'), ('Admin', 'Admin'), ('Staff', 'Staff')], max_length=225)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
