# Generated by Django 4.0.3 on 2024-01-23 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='internuser',
            name='doj',
        ),
        migrations.AlterField(
            model_name='internuser',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Priority must be at least 1'), django.core.validators.MaxValueValidator(10, message='Priority cannot be above 10')]),
        ),
    ]
